on:
    push:
        paths:
        - 'archinstall/locales/**'
    pull_request:
        paths:
        - 'archinstall/locales/**'
name: translation file checks
jobs:
    translation-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                  packages: gettext
                  version: 1.0

            - name: show translation files
              run: |
                  cd archinstall/locales
                  pwd
                  ls -l
                  bash locales_generator.sh
                  git diff --name-only
                  ls
